### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by aleeeee1** [Mroik/animeunity-video-downloader#2]
I'm trying the following:
`
python script.py --all https://animeunity.it/anime/2100-the-daily-life-of-the-immortal-king/
`

error:

`
Traceback (most recent call last):
  File "C:\Users\Ale\Desktop\animeunity-video-downloader\script.py", line 156, in <module>
    main(args.url, episode)
  File "C:\Users\Ale\Desktop\animeunity-video-downloader\script.py", line 79, in main
    scws_id = unity.get_scws_id(link, episode)
  File "C:\Users\Ale\Desktop\animeunity-video-downloader\script.py", line 44, in get_scws_id
    for x in anime["episodes"]:
KeyError: 'episodes'
`
repeated several times.

**Comment by AndreaCicca** [comment]
Same Errors

**Comment by Mroik** [comment]
Yeah, the backend has been changed, now it doesn't pass `episodes` as a attribute of the object anymore. This wasn't really a serious, and I myself don't use the script. I'll just archive the repo.
